#!/usr/bin/env php
<?php

	// require 'lmax.php';

	// $lmax = new Lemax;

	// $lmax->new_route('hello');
	
	@$command = $argv[1];
	@$option = $argv[2];

	$red = "\033[31m";
	$white = "\033[37m";
	$green = "\033[32m";
	$no_color = "\033[0m";
	$yellow = "\033[33m";

	function serve_project(){
		if (file_exists('index.php')) {
			echo "The Project now running on \033[32mhttp://localhost:8585\033[0m\n";
			echo "Press ctrl-c to quit\n";
			echo "Listening on http://localhost:8585 ...\n\n";
			system('php -S localhost:8585');
		} else {
			global $red;
			global $no_color;
			echo $red."\n    >> The Lemax Project has been crashed <<\n";
			echo "    >> Run This Command : [ php lmax upgrade ] <<\n\n".$no_color;
		}
	}

	function create_css_file($name){
		global $red;
		global $green;
		global $yellow;
		global $no_color;
		echo $green."The $name css file has been created successfully !\n".$no_color;
		echo $yellow."Path : /assets/css/$name.css\n".$no_color;
	}

	switch ($command) {
		case 'make-route':
			if (isset($option)) {
				echo "Route Created Successfully \n";
			} else {
				echo "Enter name of the route \n";
			}
		break;
		case 'run':
			serve_project();
		break;
		case 'make-css':
			create_css_file($argv[2]);
		break;
		default:
			echo $white."\nLemax version 2.0 Beta\n".$no_color
			.$white."\nAvailable commands : \n".$no_color
			.$green."    run	                   	 ".$white."run the project \n".$no_color
			.$green."    make-route	[ NAME ]  	 ".$white."make the route".$red." With *Module \n".$no_color
			.$green."    make-route 	[ NAME ]  -n     ".$white."make the route".$red." WithOut *Module \n"
			.$no_color
			.$green."    make-css	[ NAME ]    	 ".$white."make the css file \n".$no_color
			.$green."    make-js	[ NAME ]   	 ".$white."make the js file \n\n".$no_color
			.$green."    publish	             	 ".$white.">> Compress the project << \n"."              			 Ready project for publish \n".$no_color
			."Authors : \n"
			.$yellow."    Alireza Josheghani\n"
			."    Mohammad Hosein Ebadollahi\n\n"
			.$no_color."Credit : \n"
			.$yellow."    Github : https://github.com/josheghani-dev/lemax\n"
			."    Packagist : https://packagist.org/packages/lemax/installer\n"
			."    Webpage : http://lemax.ir\n\n".$no_color;
		break;
	}

?>